# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, verbose_name='商品名称')),
                ('gpic', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品单价')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='计量单位')),
                ('gclick', models.IntegerField(verbose_name='点击量')),
                ('gjianjie', models.CharField(max_length=200, verbose_name='商品简介')),
                ('gkucun', models.IntegerField(verbose_name='商品库存')),
                ('gcontent', models.TextField(verbose_name='商品描述')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='商品类型')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_app.TypeInfo', verbose_name='商品类型'),
        ),
    ]
