# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0002_auto_20170803_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['-id'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'ordering': ['-id'], 'verbose_name': '商品类型信息', 'verbose_name_plural': '商品类型信息'},
        ),
    ]
